global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Data Processing Service
  - job_name: 'data-processing'
    static_configs:
      - targets: ['data-processing:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Analytics Service
  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Data Ingestion Service
  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Notification Service
  - job_name: 'notification'
    static_configs:
      - targets: ['notification:8004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
